spring:
#数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-m5e555a0r6n7azv4hdo.mysql.rds.aliyuncs.com:3306/youjianew?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
    username: youjia
    password: Youjia1234
  # 配置初始化大小、最小、最大
    initialSize: 20
    minIdle: 20
    maxActive: 200
  # 配置获取连接等待超时的时间
    maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
   # 打开PSCache，并且指定每个连接上PSCache的大小。如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false。
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的filters
    filters: stat

  #jpa配置
    jpa:
      database: mysql
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update

  data:
    mongodb:
      host: 118.190.151.150
      port: 27017
      database: youjia
  resources:
    static-locations: classpath:/apidoc/

  redis:
      database: 0
    # Redis服务器地址
      host: 118.190.151.150
    # Redis服务器连接端口
      port: 7379

      timeout: 0

    # 连接池最大连接数（使用负值表示没有限制）
      pool:
        max-active: -1
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接池中的最大空闲连接
        max-idle: 40
    # 连接池中的最小空闲连接
        min-idle: 15
  jackson:
    time-zone: GMT+8

superAdministrator:
  email: mravAdmin
  pass: 88888888

accountCategories :
 id : sys000001
 name : 系统注册账号